window:
  startup_mode: Windowed
  dynamic_padding: true

font:
  normal:
    family: MesloLGS NF
    style: Regular

  bold:
    family: MesloLGS NF
    style: Bold

  italic:
    family: MesloLGS NF
    style: Italic

  bold_italic:
    family: MesloLGS NF
    style: Bold Italic

  size: 11.5

shell:
  program: /bin/zsh

key_bindings:
  - { key: Space, mods: Control, action: ToggleFullscreen }

colors:
  primary:
    background: "0x1e2030"
    foreground: "0xd9d9d9"

  cursor:
    text: "0xf0f0f0"
    cursor: "0x606060"

  normal:
    black: "0x444a73"
    red: "0xff5370"
    green: "0x4fd6be"
    yellow: "0xffc777"
    blue: "0x3e68d7"
    magenta: "0xfc7b7b"
    cyan: "0x86e1fc"
    white: "0xd0d0d0"

  bright:
    black: "0x828bb8"
    red: "0xff98a4"
    green: "0xc3e88d"
    yellow: "0xffc777"
    blue: "0x82aaff"
    magenta: "0xff966c"
    cyan: "0xb4f9f8"
    white: "0x5f8787"
# colors:
#   # Default colors
#   primary:
#     # hard contrast: background = '0x1d2021'
#     background: "0x282828"
#     # soft contrast: background = '0x32302f'
#     foreground: "0xebdbb2"

#   # Normal colors
#   normal:
#     black: "0x282828"
#     red: "0xcc241d"
#     green: "0x98971a"
#     yellow: "0xd79921"
#     blue: "0x458588"
#     magenta: "0xb16286"
#     cyan: "0x689d6a"
#     white: "0xa89984"

#   # Bright colors
#   bright:
#     black: "0x928374"
#     red: "0xfb4934"
#     green: "0xb8bb26"
#     yellow: "0xfabd2f"
#     blue: "0x83a598"
#     magenta: "0xd3869b"
#     cyan: "0x8ec07c"
#     white: "0xebdbb2"
