add_newline = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
min_time = 200

[kubernetes]
disabled = true
[kubernetes.context_aliases]
"gke_teko-development-staging_asia-southeast1-a_default" = "stag"
"gke_teko-development_asia-southeast1-a_teko-develop" = "dev"
"gke_teko-development_asia-southeast1-a_test-1" = "test1"

[directory]
truncate_to_repo = false
truncation_length = 6
truncation_symbol = "…/"
style = "bold green"

[gcloud]
disabled = true

[battery]
disabled = false
[battery.display]
threshold = 60
style = "bold red"
