add_newline = true

[python]
pyenv_version_name = true

[username]
disabled = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
min_time = 150

[kubernetes]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 6
truncation_symbol = "…/"
style = "bold green"

[gcloud]
disabled = true
symbol = "☁️  "

[battery]
disabled = false
[battery.display]
threshold = 60
style = "bold red"
