filetype off
call plug#begin('~/.vim/plugged')
Plug 'leafgarland/typescript-vim'
Plug 'mxw/vim-jsx'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all'  }
Plug 'junegunn/fzf.vim'
Plug 'airblade/vim-gitgutter'
Plug 'wakatime/vim-wakatime'
Plug 'Yggdroot/indentLine'
Plug 'sheerun/vim-polyglot'
Plug 'rust-lang/rust.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-commentary'
call plug#end()
filetype on

let mapleader = ","
nmap <tab> :NERDTreeToggle<cr>
nmap <leader>p :Files<cr>
nmap <leader>r :Rg<cr>
nmap <leader>w :Windows<cr>

filetype plugin indent on
set termguicolors
set t_Co=256
set nocompatible
syntax on
set shell=/bin/bash
set wrap
set regexpengine=1
set noshowcmd
set updatetime=10
set autoindent
set clipboard=unnamed
set colorcolumn=0
set signcolumn=yes
set encoding=utf-8 nobomb
set hlsearch
set noignorecase
set incsearch
set lazyredraw
set mousehide
set mouse=a
set number numberwidth=5 relativenumber
set fillchars+=vert:│
set ruler

set synmaxcol=200"
