window:
  startup_mode: Windowed
  dynamic_padding: true

cursor:
  style:
    shape: Beam
    blinking: Always
  blink_interval: 500
  unfocused_hollow: true
  thickness: 0.15

font:
  normal:
    family: Hack Nerd Font
    style: Regular

  bold:
    family: Hack Nerd Font
    style: Bold

  italic:
    family: Hack Nerd Font
    style: Italic

  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

  size: 12

shell:
  program: /bin/zsh

colors:
  # solzrized8
  primary:
    background: '0x002b36'
    foreground: '0x839496'

  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'

  # vscode
  # primary:
  #   background: "#1e1e1e"
  #   foreground: "#d4d4d4"
  # cursor:
  #   text: "#d4d4d4"
  #   cursor: "#d4d4d4"
  # normal:
  #   black: "#1e1e1e"
  #   red: "#f44747"
  #   green: "#608b4e"
  #   yellow: "#dcdcaa"
  #   blue: "#569cd6"
  #   magenta: "#c678dd"
  #   cyan: "#56b6c2"
  #   white: "#d4d4d4"
  # bright:
  #   black: "#545454"
  #   red: "#f44747"
  #   green: "#608b4e"
  #   yellow: "#dcdcaa"
  #   blue: "#569cd6"
  #   magenta: "#c678dd"
  #   cyan: "#56b6c2"
  #   white: "#d4d4d4"
