window:
  startup_mode: Windowed
  dynamic_padding: true

cursor:
  style:
    shape: Beam
    blinking: Always
  blink_interval: 500
  unfocused_hollow: true
  thickness: 0.15

font:
  normal:
    family: Hack Nerd Font
    style: Regular

  bold:
    family: Hack Nerd Font
    style: Bold

  italic:
    family: Hack Nerd Font
    style: Italic

  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

  size: 12

shell:
  program: /bin/zsh

colors:
  # solzrized8
  primary:
    background: '#002b36'
    foreground: '#839496'

  normal:
    black:   '#073642'
    red:     '#dc322f'
    green:   '#859900'
    yellow:  '#b58900'
    blue:    '#268bd2'
    magenta: '#d33682'
    cyan:    '#2aa198'
    white:   '#eee8d5'

  bright:
    black:   '#002b36'
    red:     '#cb4b16'
    green:   '#586e75'
    yellow:  '#657b83'
    blue:    '#839496'
    magenta: '#6c71c4'
    cyan:    '#93a1a1'
    white:   '#fdf6e3'
