window:
  startup_mode: Windowed
  dynamic_padding: true

font:
  normal:
    family: Hack Nerd Font
    style: Regular

  bold:
    family: Hack Nerd Font
    style: Bold

  italic:
    family: Hack Nerd Font
    style: Italic

  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

  size: 14

shell:
  program: /bin/zsh

key_bindings:
  - { key: Space, mods: Control, action: ToggleFullscreen }

colors:
  primary:
    background: "#1e1e1e"
    foreground: "#d4d4d4"
  cursor:
    text: "#d4d4d4"
    cursor: "#d4d4d4"
  normal:
    black: "#1e1e1e"
    red: "#f44747"
    green: "#608b4e"
    yellow: "#dcdcaa"
    blue: "#569cd6"
    magenta: "#c678dd"
    cyan: "#56b6c2"
    white: "#d4d4d4"
  bright:
    black: "#545454"
    red: "#f44747"
    green: "#608b4e"
    yellow: "#dcdcaa"
    blue: "#569cd6"
    magenta: "#c678dd"
    cyan: "#56b6c2"
    white: "#d4d4d4"
