window:
  startup_mode: Windowed
  dynamic_padding: true

cursor:
  style:
    shape: Beam
    blinking: Always
  blink_interval: 500
  unfocused_hollow: true
  thickness: 0.15

font:
  normal:
    family: Hack Nerd Font
    style: Regular

  bold:
    family: Hack Nerd Font
    style: Bold

  italic:
    family: Hack Nerd Font
    style: Italic

  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

  size: 10

colors:
  primary:
    background: '0x0d1117'
    foreground: '0xecf2f8'
  cursor:
    text: '0xecf2f8'
    cursor: '0x89929b'

  # Normal colors
  normal:
    black:   '0x0d1117'
    red:     '0xfa7970'
    green:   '0x7ce38b'
    yellow:  '0xfeff00'
    blue:    '0x77bdfb'
    magenta: '0xcc00ff'
    cyan:    '0x06d6c5'
    white:   '0xecf2f8'

  # Bright colors
  bright:
    black:   '0x0d1117'
    red:     '0xfa7970'
    green:   '0x7ce38b'
    yellow:  '0xfeff00'
    blue:    '0x77bdfb'
    magenta: '0xcc00ff'
    cyan:    '0x06d6c5'
    white:   '0xecf2f8'
