#!/usr/bin/env bash

branch=$1
submit=$2
for file in $(rg -l "CATALOGUE-$branch"); do
    if [[ ! -z $submit ]]; then
        pytest -p no:warnings --tb=short $file --submit
    else
        pytest -p no:warnings --tb=short $file
    fi
done
