idle_bg = "#1e1e1e" # nord0
idle_fg = "#569cd6" # light blue
info_bg = "#3274ab" # dark blue
info_fg = "#1e1e1e" # nord0
good_bg = "#608b4e" # green
good_fg = "#1e1e1e" # nord0
warning_bg = "#dcdcaa" # yellow
warning_fg = "#1e1e1e" # nord0
critical_bg = "#f44747" # red
critical_fg = "#1e1e1e" # nord0
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
