#!/usr/bin/env zsh

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.local/google-cloud-sdk/bin:$PATH
export OPENSSL_CONF=/etc/ssl/           # fix: vagrant not found openssl lib
export OS=$(uname -s | tr "[:upper:]" "[:lower:]")

export GOPATH=$HOME/Development/go
export GO111MODULE=on
export GOROOT=/home/nkthanh/.local/go
export PATH=$PATH:$GOPATH/bin

export PATH="$PATH:/usr/local/bin/mockery"

export PYTHONDONTWRITEBYTECODE=1
export VIRTUAL_ENV_DISABLE_PROMPT=1
export PYENV_ROOT="$HOME/.pyenv"
export PIPENV_PYTHON="$PYENV_ROOT/shims/python"
export PATH=$PYENV_ROOT/bin:$PATH
export PATH=$PYENV_ROOT/shims:$PATH

source $HOME/.cargo/env

. "$HOME/.cargo/env"
export BAT_THEME="Coldark-Dark"
export EDITOR=nvim
