#!/usr/bin/env zsh

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.local/google-cloud-sdk/bin:$PATH
export OPENSSL_CONF=/etc/ssl/           # fix: vagrant not found openssl lib
export OS=$(uname -s | tr "[:upper:]" "[:lower:]")

export TERMINFO=/usr/share/terminfo

export JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | cut -d'=' -f2 | xargs)
export PATH=$JAVA_HOME/bin:$PATH

export GOPATH=$HOME/Development/go
export GO111MODULE=on
export GOROOT=/usr/local/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

export PATH="$PATH:/usr/local/bin/mockery"

export PYTHONDONTWRITEBYTECODE=1
export VIRTUAL_ENV_DISABLE_PROMPT=1
export PIPENV_PYTHON="$PYENV_ROOT/shims/python"
export PYENV_ROOT="$HOME/.pyenv"
export PATH=$PYENV_ROOT/bin:$PATH
export PATH=$PYENV_ROOT/shims:$PATH

source $HOME/.cargo/env

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --exclude venv'
export FZF_COMPLETION_OPTS='+c -x'
export FZF_DEFAULT_OPTS='--preview "preview {}" --reverse'

export ZSH_CONFIG=$HOME/dotfiles/zsh
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#6eb579"
. "$HOME/.cargo/env"

export BAT_THEME="Visual Studio Dark+"
