#!/usr/bin/env zsh

export ZSH="$HOME/.oh-my-zsh"

plugins=(
  git
  jsontools
  gcloud
  kubectl
  docker
  zsh-autosuggestions
  zsh-z
  rust
  rustup
  cargo
)

source $ZSH/oh-my-zsh.sh
[ -f ~/.fzf.zsh  ] && source ~/.fzf.zsh

alias genssl="openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout cert.key -out cert.crt"
alias genmacaddr="openssl rand -hex 6 | sed 's/\(..\)/\1:/g;s/.$//'"
alias -s {yml,yaml,jsx,html,txt,c,cpp,java,go,md,json,Dockerfile,gitignore,dockerignore}=nvim
alias reload="exec \"$SHELL\""
alias md="mkdir"
alias rmwp="find . -type f -name '*.py' -exec sed -i '' 's/[[:space:]]\{1,\}$//' {} \+"
alias f="fzf"
if [[ $OS = "linux" ]]; then
  alias fd="fdfind"
fi
alias t="$HOME/dotfiles/zsh/tmux-startup.sh"
alias bat="bat --theme OneHalfDark"

eval "$(starship init zsh)"

autoload -Uz compinit

if [[ $OS == "darwin" ]]; then
    if [ $(date +'%j') != $(/usr/bin/stat -f '%Sm' -t '%j' ${ZDOTDIR:-$HOME}/.zcompdump) ]; then
        compinit;
    else
        compinit -C;
    fi
fi

my_loader=$ZSH_CONFIG/autoloaded
fpath=(
    $my_loader
    $fpath
)
if [[ -d $my_loader ]]; then
    for func in $my_loader/*; do
        autoload -Uz ${func:t}
    done
fi
unset my_loader
