#!/usr/bin/env zsh

head -n7 $HOME/dotfiles/README.md

export ZSH="$HOME/.oh-my-zsh"

plugins=(
  git
  jsontools
  gcloud
  kubectl
  docker
  zsh-autosuggestions
  zsh-z
  yarn
  vi-mode
)

source $ZSH/oh-my-zsh.sh

alias genssl="openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout cert.key -out cert.crt"
alias genmacaddr="openssl rand -hex 6 | sed 's/\(..\)/\1:/g;s/.$//'"
alias reload="exec \"$SHELL\""
alias md="mkdir"
if [[ $OS = "linux" ]]; then
   alias fd="fdfind"
   alias open="xdg-open"
   alias pbcopy="xclip -sel clip"
   alias pbpaste="xclip -o -sel clip"
fi
alias ls="exa"
alias ll="exa --long"
alias lt="exa --tree"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias pt="poetry"
alias v="nvim"
alias cl="clear"

autoload -Uz compinit

if [[ $OS == "darwin" ]]; then
    if [ $(date +'%j') != $(/usr/bin/stat -f '%Sm' -t '%j' ${ZDOTDIR:-$HOME}/.zcompdump) ]; then
        compinit;
    else
        compinit -C;
    fi
fi

my_loader=$ZSH_CONFIG/autoloaded
fpath=(
    $my_loader
    $fpath
)
if [[ -d $my_loader ]]; then
    for func in $my_loader/*; do
        autoload -Uz ${func:t}
    done
fi
unset my_loader

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(starship init zsh)"
eval "$(pyenv init -)"
eval "$(zoxide init zsh)"
