k9s:
  body:
    fgColor: "#ecf2f8"
    bgColor: "#0d1117"
    logoColor: "#5af78e"
  prompt:
    fgColor: "#ecf2f8"
    bgColor: "#0d1117"
    suggestColor: "#5af78e"
  info:
    fgColor: "#ecf2f8"
    sectionColor: "#5af78e"
  dialog:
    fgColor: "#ecf2f8"
    bgColor: "#0d1117"
    buttonFgColor: "#97979b"
    buttonBgColor: "#212b30"
    buttonFocusFgColor: "#97979b"
    buttonFocusBgColor: "#5af78e"
    labelFgColor: "#97979b"
    fieldFgColor: "#5af78e"
  frame:
    border:
      fgColor: "#5af78e"
      focusColor: "#5af78e"
    menu:
      fgColor: "#ecf2f8"
      keyColor: "#57c7ff"
      numKeyColor: "#ff6ac1"
    crumbs:
      fgColor: "#212b30"
      bgColor: white
      activeColor: "#f3f99d"
    status:
      newColor: "#eff0eb"
      modifyColor: "#5af78e"
      addColor: "#57c7ff"
      errorColor: "#ff5c57"
      highlightColor: "#f3f99d"
      killColor: mediumpurple
      completedColor: gray
    title:
      fgColor: "#5af78e"
      bgColor: "#0d1117"
      highlightColor: white
      counterColor: white
      filterColor: "#57c7ff"
  views:
    # Charts skins...
    charts:
      bgColor: "#0d1117"
      defaultDialColors:
        - "#57c7ff"
        - "#ff5c57"
      defaultChartColors:
        - "#57c7ff"
        - "#ff5c57"
    table:
      fgColor: "#57c7ff"
      markColor: darkgoldenrod
      bgColor: "#0d1117"
      header:
        fgColor: white
        bgColor: "#0d1117"
        sorterColor: orange
    xray:
      fgColor: "#57c7ff"
      bgColor: "#212b30"
      cursorColor: "#5af78e"
      graphicColor: darkgoldenrod
      showIcons: false
    yaml:
      keyColor: "#ff5c57"
      colonColor: white
      valueColor: "#f3f99d"
    logs:
      fgColor: white
      bgColor: "#0d1117"
      indicator:
        fgColor: white
        bgColor: "#0d1117"
